chore: debugging helm push

diff --git a/.github/actions/artefact-push/action.yml b/.github/actions/artefact-push/action.yml
--- a/.github/actions/artefact-push/action.yml
+++ b/.github/actions/artefact-push/action.yml
@@ -169,35 +169,44 @@ runs:
       if: ${{ steps.detect-values.outputs.scheme == 'helm' }}
       uses: dragoscirjan/github-tools/.github/actions/helm-setup@main
 
+    - name: Helm Authentication Required
+      if: ${{ ! inputs.username || ! inputs.password }}
+      shell: bash
+      run: |
+        echo "Helm authentication required"
+        exit 1
+
     # - name: Package Helm Chart
     #   if: ${{ steps.detect-values.outputs.scheme == 'helm' }}
     #   run: |
     #     helm package ${{ inputs.artifact }} --version ${{ inputs.version }}
     #     ls -la
 
-    # - name: Determine Helm Repository Type
-    #   id: helm-repo-type
-    #   if: ${{ steps.detect-values.outputs.scheme == 'helm' }}
-    #   shell: bash
-    #   run: |
-    #     destination="${{ steps.detect-values.outputs.destination }}"
-    #     if [[ "$destination" == oci://* ]]; then
-    #       echo "oci_repo=true" >> $GITHUB_OUTPUT
-    #     else
-    #       echo "oci_repo=false" >> $GITHUB_OUTPUT
+    - name: Determine Helm Repository Type
+      id: helm-repo-type
+      if: ${{ steps.detect-values.outputs.scheme == 'helm' }}
+      shell: bash
+      run: |
+        destination="${{ steps.detect-values.outputs.destination }}"
+        if [[ "$destination" == oci://* ]]; then
+          echo "oci_repo=true" >> $GITHUB_OUTPUT
+        else
+          echo "oci_repo=false" >> $GITHUB_OUTPUT
 
-    # - name: Helm OCI Authentication
-    #   if: ${{ steps.detect-values.outputs.scheme == 'helm' && steps.helm-repo-type.outputs.oci_repo == 'true' && inputs.username && inputs.password }}
-    #   run: |
-    #     helm registry login ${{ steps.detect-values.outputs.destination }} \
-    #       --username ${{ inputs.username }} \
-    #       --password ${{ inputs.password }}
+    - name: Helm OCI Authentication
+      if: ${{ steps.detect-values.outputs.scheme == 'helm' && steps.helm-repo-type.outputs.oci_repo == 'true' }}
+      shell: bash
+      run: |
+        helm registry login ${{ steps.detect-values.outputs.destination }} \
+          --username ${{ inputs.username }} \
+          --password ${{ inputs.password }}
 
-    # - name: Push Helm Chart to OCI Registry
-    #   if: ${{ steps.detect-values.outputs.scheme == 'helm' && steps.helm-repo-type.outputs.oci_repo == 'true' }}
-    #   run: |
-    #     chart_package=$(ls *.tgz)
-    #     helm push $chart_package ${{ steps.detect-values.outputs.destination }}
+    - name: Push Helm Chart to OCI Registry
+      if: ${{ steps.detect-values.outputs.scheme == 'helm' && steps.helm-repo-type.outputs.oci_repo == 'true' }}
+      shell: bash
+      run: |
+        chart_package=$(ls *.tgz)
+        helm push $chart_package ${{ steps.detect-values.outputs.destination }}
 
     # - name: Install Helm Push Plugin
     #   if: ${{ steps.detect-values.outputs.scheme == 'helm' && steps.helm-repo-type.outputs.oci_repo == 'false' }}
